var nameList = [
  "Time",
  "Past",
  "Future",
  "Dev",
  "Fly",
  "Flying",
  "Soar",
  "Soaring",
  "Power",
  "Falling",
  "Fall",
  "Jump",
  "Cliff",
  "Mountain",
  "Rend",
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Gold",
  "Demon",
  "Demonic",
  "Panda",
  "Cat",
  "Kitty",
  "Kitten",
  "Zero",
  "Memory",
  "Trooper",
  "XX",
  "Bandit",
  "Fear",
  "Light",
  "Glow",
  "Tread",
  "Deep",
  "Deeper",
  "Deepest",
  "Mine",
  "Your",
  "Worst",
  "Enemy",
  "Hostile",
  "Force",
  "Video",
  "Game",
  "Donkey",
  "Mule",
  "Colt",
  "Cult",
  "Cultist",
  "Magnum",
  "Gun",
  "Assault",
  "Recon",
  "Trap",
  "Trapper",
  "Redeem",
  "Code",
  "Script",
  "Writer",
  "Near",
  "Close",
  "Open",
  "Cube",
  "Circle",
  "Geo",
  "Genome",
  "Germ",
  "Spaz",
  "Shot",
  "Echo",
  "Beta",
  "Alpha",
  "Gamma",
  "Omega",
  "Seal",
  "Squid",
  "Money",
  "Cash",
  "Lord",
  "King",
  "Duke",
  "Rest",
  "Fire",
  "Flame",
  "Morrow",
  "Break",
  "Breaker",
  "Numb",
  "Ice",
  "Cold",
  "Rotten",
  "Sick",
  "Sickly",
  "Janitor",
  "Camel",
  "Rooster",
  "Sand",
  "Desert",
  "Dessert",
  "Hurdle",
  "Racer",
  "Eraser",
  "Erase",
  "Big",
  "Small",
  "Short",
  "Tall",
  "Sith",
  "Bounty",
  "Hunter",
  "Cracked",
  "Broken",
  "Sad",
  "Happy",
  "Joy",
  "Joyful",
  "Crimson",
  "Destiny",
  "Deceit",
  "Lies",
  "Lie",
  "Honest",
  "Destined",
  "Bloxxer",
  "Hawk",
  "Eagle",
  "Hawker",
  "Walker",
  "Zombie",
  "Sarge",
  "Capt",
  "Captain",
  "Punch",
  "One",
  "Two",
  "Uno",
  "Slice",
  "Slash",
  "Melt",
  "Melted",
  "Melting",
  "Fell",
  "Wolf",
  "Hound",
  "Legacy",
  "Sharp",
  "Dead",
  "Mew",
  "Chuckle",
  "Bubba",
  "Bubble",
  "Sandwich",
  "Smasher",
  "Extreme",
  "Multi",
  "Universe",
  "Ultimate",
  "Death",
  "Ready",
  "Monkey",
  "Elevator",
  "Wrench",
  "Grease",
  "Head",
  "Theme",
  "Grand",
  "Cool",
  "Kid",
  "Boy",
  "Girl",
  "Vortex",
  "Paradox",
];

var commentList = [
  "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
  "I hate to hear you talk about all women as if they were fine ladies instead of rational creatures.",
  "Silly things do cease to be silly if they are done by sensible people in an impudent way.",
  "Give a girl an education and introduce her properly into the world,",
  "Life seems but a quick succession of busy nothings.",
  "Our scars make us know that our past was for real.",
  "I cannot speak well enough to be unintelligible.",
  "One cannot be always laughing at a man without now and then stumbling on something witty.",
  "Men were put into the world to teach women the law of compromise.",
  "The person, be it gentlemen or lady, who has not pleasure in a good novel, must be intolerably stupid.",
  "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
  "I hate to hear you talk about all women as if they were fine ladies instead of rational creatures.",
  "Silly things do cease to be silly if they are done by sensible people in an impudent way.",
  "Give a girl an education and introduce her properly into the world,",
  "Life seems but a quick succession of busy nothings.",
  "Our scars make us know that our past was for real.",
  "I cannot speak well enough to be unintelligible.",
  "One cannot be always laughing at a man without now and then stumbling on something witty.",
  "Men were put into the world to teach women the law of compromise.",
  "The person, be it gentlemen or lady, who has not pleasure in a good novel, must be intolerably stupid.",
  "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
  "I hate to hear you talk about all women as if they were fine ladies instead of rational creatures.",
  "Silly things do cease to be silly if they are done by sensible people in an impudent way.",
  "Give a girl an education and introduce her properly into the world,",
  "Life seems but a quick succession of busy nothings.",
  "Our scars make us know that our past was for real.",
  "I cannot speak well enough to be unintelligible.",
  "One cannot be always laughing at a man without now and then stumbling on something witty.",
  "Men were put into the world to teach women the law of compromise.",
  "The person, be it gentlemen or lady, who has not pleasure in a good novel, must be intolerably stupid.",
  "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
  "I hate to hear you talk about all women as if they were fine ladies instead of rational creatures.",
  "Silly things do cease to be silly if they are done by sensible people in an impudent way.",
  "Give a girl an education and introduce her properly into the world,",
  "Life seems but a quick succession of busy nothings.",
  "Our scars make us know that our past was for real.",
  "I cannot speak well enough to be unintelligible.",
  "One cannot be always laughing at a man without now and then stumbling on something witty.",
  "Men were put into the world to teach women the law of compromise.",
  "The person, be it gentlemen or lady, who has not pleasure in a good novel, must be intolerably stupid.",
  "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
  "I hate to hear you talk about all women as if they were fine ladies instead of rational creatures.",
  "Silly things do cease to be silly if they are done by sensible people in an impudent way.",
  "Give a girl an education and introduce her properly into the world,",
  "Life seems but a quick succession of busy nothings.",
  "Our scars make us know that our past was for real.",
  "I cannot speak well enough to be unintelligible.",
  "One cannot be always laughing at a man without now and then stumbling on something witty.",
  "Men were put into the world to teach women the law of compromise.",
  "The person, be it gentlemen or lady, who has not pleasure in a good novel, must be intolerably stupid.",
  "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
  "I hate to hear you talk about all women as if they were fine ladies instead of rational creatures.",
  "Silly things do cease to be silly if they are done by sensible people in an impudent way.",
  "Give a girl an education and introduce her properly into the world,",
  "Life seems but a quick succession of busy nothings.",
  "Our scars make us know that our past was for real.",
  "I cannot speak well enough to be unintelligible.",
  "One cannot be always laughing at a man without now and then stumbling on something witty.",
  "Men were put into the world to teach women the law of compromise.",
  "The person, be it gentlemen or lady, who has not pleasure in a good novel, must be intolerably stupid.",
  "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
  "I hate to hear you talk about all women as if they were fine ladies instead of rational creatures.",
  "Silly things do cease to be silly if they are done by sensible people in an impudent way.",
  "Give a girl an education and introduce her properly into the world,",
  "Life seems but a quick succession of busy nothings.",
  "Our scars make us know that our past was for real.",
  "I cannot speak well enough to be unintelligible.",
  "One cannot be always laughing at a man without now and then stumbling on something witty.",
  "Men were put into the world to teach women the law of compromise.",
  "The person, be it gentlemen or lady, who has not pleasure in a good novel, must be intolerably stupid.",
  "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
];

export const countryList = [
  { regionCode: "AE", countryName: "United Arab Emirates" },
  { regionCode: "BH", countryName: "Bahrain" },
  { regionCode: "DZ", countryName: "Algeria" },
  { regionCode: "EG", countryName: "Egypt" },
  { regionCode: "IQ", countryName: "Iraq" },
  { regionCode: "JO", countryName: "Jordan" },
  { regionCode: "KW", countryName: "Kuwait" },
  { regionCode: "LB", countryName: "Lebanon" },
  { regionCode: "LY", countryName: "Libya" },
  { regionCode: "MA", countryName: "Morocco" },
  { regionCode: "OM", countryName: "Oman" },
  { regionCode: "QA", countryName: "Qatar" },
  { regionCode: "SA", countryName: "Saudi Arabia" },
  { regionCode: "TN", countryName: "Tunisia" },
  { regionCode: "YE", countryName: "Yemen" },
  { regionCode: "AZ", countryName: "Azerbaijan" },
  { regionCode: "BY", countryName: "Belarus" },
  { regionCode: "BG", countryName: "Bulgaria" },
  { regionCode: "BD", countryName: "Bangladesh" },
  { regionCode: "BA", countryName: "Bosnia and Herzegovina" },
  { regionCode: "CZ", countryName: "Czech Republic" },
  { regionCode: "DK", countryName: "Denmark" },
  { regionCode: "AT", countryName: "Austria" },
  { regionCode: "CH", countryName: "Switzerland" },
  { regionCode: "DE", countryName: "Germany" },
  { regionCode: "GR", countryName: "Greece" },
  { regionCode: "AU", countryName: "Australia" },
  { regionCode: "BE", countryName: "Belgium" },
  { regionCode: "CA", countryName: "Canada" },
  { regionCode: "GB", countryName: "United Kingdom" },
  { regionCode: "GH", countryName: "Ghana" },
  { regionCode: "IE", countryName: "Ireland" },
  { regionCode: "IL", countryName: "Israel" },
  { regionCode: "IN", countryName: "India" },
  { regionCode: "JM", countryName: "Jamaica" },
  { regionCode: "KE", countryName: "Kenya" },
  { regionCode: "MT", countryName: "Malta" },
  { regionCode: "NG", countryName: "Nigeria" },
  { regionCode: "NZ", countryName: "New Zealand" },
  { regionCode: "SG", countryName: "Singapore" },
  { regionCode: "UG", countryName: "Uganda" },
  { regionCode: "US", countryName: "United States" },
  { regionCode: "ZA", countryName: "South Africa" },
  { regionCode: "ZW", countryName: "Zimbabwe" },
  { regionCode: "AR", countryName: "Argentina" },
  { regionCode: "BO", countryName: "Bolivia" },
  { regionCode: "CL", countryName: "Chile" },
  { regionCode: "CO", countryName: "Colombia" },
  { regionCode: "CR", countryName: "Costa Rica" },
  { regionCode: "DO", countryName: "Dominican Republic" },
  { regionCode: "EC", countryName: "Ecuador" },
  { regionCode: "ES", countryName: "Spain" },
  { regionCode: "GT", countryName: "Guatemala" },
  { regionCode: "HN", countryName: "Honduras" },
  { regionCode: "MX", countryName: "Mexico" },
  { regionCode: "NI", countryName: "Nicaragua" },
  { regionCode: "PA", countryName: "Panama" },
  { regionCode: "PE", countryName: "Peru" },
  { regionCode: "PR", countryName: "Puerto Rico" },
  { regionCode: "PY", countryName: "Paraguay" },
  { regionCode: "SV", countryName: "El Salvador" },
  { regionCode: "UY", countryName: "Uruguay" },
  { regionCode: "VE", countryName: "Venezuela" },
  { regionCode: "EE", countryName: "Estonia" },
  { regionCode: "FI", countryName: "Finland" },
  { regionCode: "PH", countryName: "Philippines" },
  { regionCode: "FR", countryName: "France" },
  { regionCode: "SN", countryName: "Senegal" },
  { regionCode: "HR", countryName: "Croatia" },
  { regionCode: "HU", countryName: "Hungary" },
  { regionCode: "ID", countryName: "Indonesia" },
  { regionCode: "IS", countryName: "Iceland" },
  { regionCode: "IT", countryName: "Italy" },
  { regionCode: "JP", countryName: "Japan" },
  { regionCode: "GE", countryName: "Georgia" },
  { regionCode: "KZ", countryName: "Kazakhstan" },
  { regionCode: "KR", countryName: "South Korea" },
  { regionCode: "LU", countryName: "Luxembourg" },
  { regionCode: "LA", countryName: "Laos" },
  { regionCode: "LT", countryName: "Lithuania" },
  { regionCode: "LV", countryName: "Latvia" },
  { regionCode: "MK", countryName: "North Macedonia" },
  { regionCode: "MY", countryName: "Malaysia" },
  { regionCode: "NO", countryName: "Norway" },
  { regionCode: "NP", countryName: "Nepal" },
  { regionCode: "NL", countryName: "Netherlands" },
  { regionCode: "PL", countryName: "Poland" },
  { regionCode: "BR", countryName: "Brazil" },
  { regionCode: "PT", countryName: "Portugal" },
  { regionCode: "RO", countryName: "Romania" },
  { regionCode: "RU", countryName: "Russia" },
  { regionCode: "LK", countryName: "Sri Lanka" },
  { regionCode: "SK", countryName: "Slovakia" },
  { regionCode: "SI", countryName: "Slovenia" },
  { regionCode: "ME", countryName: "Montenegro" },
  { regionCode: "RS", countryName: "Serbia" },
  { regionCode: "SE", countryName: "Sweden" },
  { regionCode: "TZ", countryName: "Tanzania" },
  { regionCode: "TH", countryName: "Thailand" },
  { regionCode: "TR", countryName: "Turkey" },
  { regionCode: "UA", countryName: "Ukraine" },
  { regionCode: "PK", countryName: "Pakistan" },
  { regionCode: "VN", countryName: "Vietnam" },
  { regionCode: "HK", countryName: "Hong Kong" },
  { regionCode: "TW", countryName: "Taiwan" },
  { regionCode: "CY", countryName: "Cyprus" },
  { regionCode: "KH", countryName: "Cambodia" },
  { regionCode: "LI", countryName: "Liechtenstein" },
  { regionCode: "PG", countryName: "Papua New Guinea" },
];

export function generateName() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}
export function generateComment() {
  return commentList[Math.floor(Math.random() * commentList.length)];
}
